config/routes.rb
Gtree::Application.routes.draw do
  
  resources :tabs do
    resources :comments
  end
  
  match "/login" => "user_sessions#new", :as => "login"
  match "/logout" => "user_sessions#destroy", :as => "logout"
  
  match "user_tab" => "tabs#index_user", :as => "user_tab"

  resource :user_session

  resources :users

  root :to => "tabs#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tab
end

app/models/tab.rb
class Tab < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  is_gravtastic!
  acts_as_authentic
  has_many :tabs
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all

  protect_from_forgery 

  helper_method :current_user, :current_user_session

  before_filter :set_locale

  private

  def set_locale
    if params[:locale]
      I18n.locale = params[:locale]
    else
      if current_user
        if current_user.language
          I18n.locale = current_user.language
        end
      end
    end
  end

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
  
  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_url
      return false
    end
  end

  def require_no_user
    if current_user
      store_location
      flash[:notice] = "You must be logged out to access this page"
      redirect_to account_url
      return false
    end
  end
  
  def store_location
    session[:return_to] = request.request_uri
  end
  
  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @tab = Tab.find(params[:tab_id])
    @comment = @tab.comments.build(params[:comment])
    if current_user
      @comment.user_id = current_user.id
    else
      @comment.user_id = 0;
    end
    @comment.save!
    redirect_to @tab
  end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  # GET /tabs
  # GET /tabs.xml
  def index
      @tabs = Tab.paginate :per_page => 10, :page => params[:page], 
                           :conditions => ['(title LIKE ? OR tag LIKE ?) AND user_id LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:user_id]}%"],
                           :order => params[:order_by]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tabs }
    end
  end

  # GET /tabs/1
  # GET /tabs/1.xml
  def show
    @tab = Tab.find(params[:id])
    if @tab.counter == nil
      @tab.counter = 1
    else
      @tab.counter = @tab.counter + 1
    end
    @tab.save

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tab }
    end
  end

  # GET /tabs/new
  # GET /tabs/new.xml
  def new
    if current_user
      @tab = Tab.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @tab }
      end
    else
      flash[:warning] = (t'flash.premission_denied') + (t'flash.cant_add_tab')
      redirect_to root_url
    end
  end

  # GET /tabs/1/edit
  def edit
    if current_user
      if current_user.id == Tab.find(params[:id]).user_id
        @tab = Tab.find(params[:id])
      else
        flash[:warning] = t'flash.premission_denied'
        redirect_to root_url
      end
    end
  end

  # POST /tabs
  # POST /tabs.xml
  def create
    @tab = Tab.new(params[:tab])
    @tab.user_id = current_user.id

    respond_to do |format|
      if @tab.save
        flash[:notice] = t'flash.tab_created'
        format.html { redirect_to(@tab) }
        format.xml  { render :xml => @tab, :status => :created, :location => @tab }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tab.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tabs/1
  # PUT /tabs/1.xml
  def update
    @tab = Tab.find(params[:id])

    respond_to do |format|
      if @tab.update_attributes(params[:tab])
        flash[:notice] = t'flash.tab_udated'
        format.html { redirect_to(@tab) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tab.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tabs/1
  # DELETE /tabs/1.xml
  def destroy
    if current_user
      @tab = Tab.find(params[:id])
      @tab.destroy

      flash[:notice] = t'flash.tab_deleted'
      redirect_to root_url
      #respond_to do |format|
      #  format.html { redirect_to(tabs_url) }
      #  format.xml  { head :ok }
      #end
    else
      flash[:warning] = t'flash.premission_denied'
      redirect_to root_url
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = t'flash.login'
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = t'flash.logout'
    redirect_back_or_default login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    if params[:id] == 'current' 
      @user = current_user
    else
      @user = User.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    if current_user
      flash[:warning] = "<strong>#{current_user.username}</strong>! You are already logged in, because you can do this after logged out"
      redirect_to root_url
    else
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = 'Registration successful.'
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = 'Successfully updated profile.'
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    #if params[:id] == 'current' || params[:id] == current_user.id
    if true
      @user = current_user
      @user.destroy

      respond_to do |format|
        format.html { redirect_to(users_url) }
        format.xml  { head :ok }
      end
    else
      flash[:warning] = 'Premission denied!'
      redirect_to edit_user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% div_for comment do %>
  <p>
  <% if comment.user_id != 0 %>
    <%= image_tag User.find(comment.user_id).gravatar_url(), :alt => '[avatar]' %>
    <strong><%= link_to User.find(comment.user_id).username, user_path(User.find(comment.user_id)) %></strong>
  <% else %>
    <%= image_tag "http://3.bp.blogspot.com/_X_wVXvHFqD8/RiZ8-Qvhq5I/AAAAAAAAATo/BiA2DnDjuOo/s400/anonymous1.jpg", :height => 50, :width => 50 %>
    <strong>Anonymous</strong>  
  <% end %>
  sayd <%= time_ago_in_words(comment.created_at) %> ago<br />
  <%= h(comment.body) %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<% form_for(@comment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Tab</th>
    <th>Body</th>
    <th>Username</th>
  </tr>

<% for comment in @comments %>
  <tr>
    <td><%=h comment.tab_id %></td>
    <td><%=h comment.body %></td>
    <td><%=h comment.username %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<% form_for(@comment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :tab_id %><br />
    <%= f.text_field :tab_id %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>Tab:</b>
  <%=h @comment.tab_id %>
</p>

<p>
  <b>Body:</b>
  <%=h @comment.body %>
</p>

<p>
  <b>Username:</b>
  <%=h @comment.username %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title><%= (@tab && @tab.title) ? @tab.title : 'Gtree' %></title>

		<%= stylesheet_link_tag 'blueprint/screen', :media => "screen, projection" %>
		<%= stylesheet_link_tag 'blueprint/print', :media => "print" %>
		<%= stylesheet_link_tag 'application' %>

		<%= javascript_include_tag "show_tab" %>
		<%= javascript_include_tag "tablature" %>
		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag "jquery" %>
		<%= javascript_include_tag :defaults %>
        <script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php" type="text/javascript"></script>
		<%= csrf_meta_tag %>
		<!--[if lt IE 8]>
		<link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection" />
		<![endif]-->
	</head>
	<body>
		<div class="container">
        <div class="span-24 last header">
		<div class="span-5 "><%= link_to image_tag("header.png"), root_url, :title => (t'home.head.logo') %></div>
        <% if current_user %>
            <div class="span-5">
        <% else %>
            <div class="span-3">
        <% end %>
			<div class="span-1"><%= link_to image_tag("home.png"), root_url, :title => (t'home.head.home') %></div>
			<div class="span-1"><%= link_to image_tag("users.png"), users_path, :title => (t'home.head.users') %></div>
		<% if current_user %>
			<div class="span-1"><%= link_to image_tag("add.png"), new_tab_path, :title => (t'home.head.add_tab') %></div>
			<div class="span-1"><%= link_to image_tag("my_tabs.png"), tabs_path(:user_id => current_user.id), :title => (t 'home.head.my_tabs') %></div>
			<div class="span-1 last"><%= image_tag 'search.png', :title => "Search", :alt => (t'home.head.search') %></div>
            </div>
            <div class="span-7">
			<% form_tag tabs_path, :method => 'get' do %>
			  <%= text_field_tag :search, params[:search] %>
			  <%= submit_tag (t'home.head.search'), :name => nil %>
			<% end %>
            </div>
            <div class="span-1">
              <%= image_tag 'flag_mn_enable.png' %>
              <%= image_tag 'flag_en_enable.png' %>
            </div>
            <div class="prepend-1 span-4 last">
		    <%= link_to current_user.username, user_path(:current), :title => (t'home.head.profile'), :id =>"current_user" %>
		    <%= image_tag current_user.gravatar_url(:size => 30), :alt => "[avatar]", :height => 30, :width => 30 %>
            </div>
		    <div class="span-1"><%= link_to image_tag("logout.png"), logout_path, :title => (t'home.head.logout') %></div>
		<% else %>
			<%= image_tag 'search.png', :title => (t'home.head.search') %>
            </div>
            <div class="span-9" style="{visiblity: hide;}">
			<% form_tag tabs_path, :method => 'get' do %>
			  <%= text_field_tag :search, params[:search] %>
			  <%= submit_tag (t'home.head.search'), :name => nil %>
			<% end %>
            </div>
            <div class="span-1">
              <%= link_to image_tag 'flag_mn_enable.png', :action => params[:locale] = 'mn' %>
              <%= image_tag 'flag_en_enable.png' %>
            </div>
            <div class="prepend-3 span-2 last">
			<%= link_to (t'home.head.register'), new_user_path, :title => (t'home.head.register') %>
            </div>
            <div class="span-1"><%= link_to image_tag("login.png"), login_path, :title => (t'home.head.login') %></div>
		<% end %>
        </div>
            
		<% flash.each do |key, msg| %>
			<div class="<%= key %>" id="alert">
			    <%= msg %>
            </div>
		<% end %>

			<div class="main">
				<%= yield %>
			</div><!-- end .mainContent -->
		</div><!-- end .container -->

		<div class="exp_footer">
			<div class="footer">
				<p>This is footer</p>
			</div><!-- end .footer -->
		</div><!-- end exp_footer -->
	</body>
</html>

app/views/tabs/index.html.erb
<h1><%= (t 'tab.index_title') %></h1>
<table class="list">
  <tr bgcolor = '#222' >
    <th><%= link_to (t 'tab.title'), tabs_path(:order_by => 'title') %> v</th>
    <th><%= link_to (t 'tab.artist'), tabs_path(:order_by => 'artist') %> v</th>
    <th><%= link_to (t 'tab.tag'), tabs_path(:order_by => 'tag') %> v</th>
    <th><%= (t 'tab.user') %></th>
    <th><%= link_to (t 'tab.created_at'), tabs_path(:order_by => 'created_at') %> v</th>
    <th>Comments</th>
    <th>Views</th>
  </tr>

<% for tab in @tabs %>
  <tr bgcolor="<%= cycle('#aaa', '#ccc') %>">
    <td><strong><%= link_to tab.title, tab %></strong></td>
    <td><%=h tab.artist %></td>
    <td><%=h tab.tag %></td>
    <td><%= link_to User.find(tab.user_id).username, User.find(tab.user_id) %></td>
    <td><%= time_ago_in_words(tab.created_at) %> ago</td>
    <td><%= tab.comments.count %></td>
    <td><%= tab.counter %></td> 
    </tr>
<% end %>
</table>

<%= will_paginate @tabs %>

app/views/tabs/index_user.html.erb
<h1><%= image_tag current_user.gravatar_url(:size => 30) %> Listing your tabs</h1>

<table>
  <tr bgcolor = "gray">
    <th>Title</th>
    <th>Artist</th>
    <th>Tag</th>
    <th></th><th></th><th></th>
  </tr>

<% for tab in @tabs %>
  <tr bgcolor="<%= cycle('white', '#ccc') %>">
    <td><h2><%= link_to tab.title, tab %></h2></td>
    <td><%=h tab.artist %></td>
    <td><%=h tab.tag %></td>
    <td><%= time_ago_in_words(tab.created_at) %> ago</td>
    <% if current_user %>
      <% if current_user.id == tab.user_id %>
        <td><%= link_to 'Edit', edit_tab_path(tab) %></td>
        <td><%= link_to 'Destroy', tab, :confirm => 'Are you sure?', :method => :delete %></td>
      <% else %>
        <td></td><td></td>
      <% end %>
    <% else %>
      <td></td><td></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if current_user %>
  <%= button_to 'New tab', new_tab_path %>
<% end %>

app/views/tabs/show.html.erb
<h1><%=h @tab.title %></h1>

<h3>by <%=h @tab.artist %></h3>
<br />
<b>Tag:</b>
<%=h @tab.tag %>
<div class="creator">
<%= image_tag User.find(@tab.user_id).gravatar_url(:size => 50), :alt => "[avatar]" %>
<br />
<%= link_to User.find(@tab.user_id).username, User.find(@tab.user_id) %> from <%= time_ago_in_words(@tab.created_at) %> ago 
</div>
<%= link_to_function "Show Text", "toggle_visibility('text')" %>
<textarea id="text" style="display:none" readonly="readonly">
  <%= @tab.tab %>
</textarea>
<pre><div id="preview"></div></pre>
<% if current_user %>
  <% if current_user.id == @tab.user_id %>
    <%= link_to 'Edit', edit_tab_path(@tab) %>
  <% end %>
<% end %>

<h2>Comments</h2>
<div id="comments">
  <%= render :partial => @tab.comments %>
</div>

<% form_for [@tab, Comment.new] do |f| %>
  <p>
    <%= f.label :body, "New comment" %><br />
    <%= f.text_area :body %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>
<%= javascript_tag "show_tab('text', 'preview')" %>

app/views/user_sessions/new.html.erb
<h1><%= t 'login.title' %></h1>

<%= form_for(@user_session, :url => user_session_path) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label (t 'login.username') %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label (t 'login.password') %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit (t 'login.login') %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t'user.edit_title' %></h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label t'user.username' %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label t'user.email' %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label t'user.password' %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label t'user.password_confirmation' %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label t'user.language' %><br />
    <%= f.select :language, [['English', 'en'], ['Монгол', 'mn']] %>
  </p>
  <p>
    <%= f.submit t'user.update' %>
  </p>
<% end %>
<%= link_to (t'user.delete'), current_user, :confirm => (t'user.are_you_sure'), :method => :delete %>

app/views/users/index.html.erb
<h1><%= t'user.index_title' %></h1>

<table>
  <tr bgcolor="gray">
    <th><%= t'user.username' %></th>
    <th><%= t'user.email' %></th>
    <th></th><th></th>
  </tr>

<% for user in @users %>
  <tr bgcolor="<%= cycle('white', '#ccc') %>">
    <td><h2><%= image_tag user.gravatar_url(:size => 30) %><%= link_to user.username, user %></h2></td>
    <td><%=h user.email %></td>
    <% if current_user %>
      <% if current_user.id == user.id %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
      <% else %>
        <td></td><td></td>
      <% end %>
    <% else %>
      <td></td><td></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1><%= t'user.registration_title' %></h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label t'user.username' %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label t'user.email' %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label t'user.password' %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label t'user.password_confirmation' %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label t'user.language' %><br />
    <%= f.select :language, [['English', 'en'], ['Монгол', 'mn']] %>
  </p>
  <p>
    <%= f.submit t'user.register' %>
  </p>
<% end %>

<%= link_to 'Back', tabs_path %>

app/views/users/show.html.erb
<% if @user == current_user %>
  <h1><%= t'user.your_profile' %></h1>
<% else %>
  <h1><%=h @user.username %></h1>
<% end %>
<p>
  <%= image_tag @user.gravatar_url %>
</p>
<p>
  <b><%= t'user.username' %>:</b>
  <%=h @user.username %>
</p>

<p>
  <b><%= t'user.email' %>:</b>
  <%=h @user.email %>
</p>

<p>
  <%= link_to @user.username, tabs_path(:user_id => @user.id) %>
</p>

<% if current_user %>
  <% if current_user.id == @user.id %>
    <%= link_to (t'user.edit'), edit_user_path(:current) %>
  <% end %>
<% end %>